import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://astrava.club';

  // These could be dynamically generated by reading the file system in a real app,
  // but static arrays work perfectly for small to medium sites.
  const tools = [
    'attendance-calculator',
    'cgpa-calculator',
    'pomodoro-timer'
  ];

  const staticPages = [
    '',
    '/tools',
    '/privacy',
    '/terms'
  ];

  const toolEntries = tools.map((tool) => ({
    url: `${baseUrl}/tools/${tool}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: 0.8,
  }));

  const staticEntries = staticPages.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'monthly' as const,
    priority: route === '' ? 1 : 0.6,
  }));

  return [...staticEntries, ...toolEntries];
}
